apiVersion: apps/v1
kind: Deployment
metadata:
  name: makers-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: makerservice
  template:
    metadata:
      labels:
        app: makerservice
    spec:
      containers:
        - name: makerservice
          image: nathanouriach/makerservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: makers-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: makerservice
  ports:
    - name: makerservice
      protocol: TCP
      port: 80
      targetPort: 80